/* DROPPERS START */

/* DROPPERS END */

DROP TRIGGER check_transaction_update ON bs_transaction;
DROP TRIGGER check_transaction_insert ON bs_transaction;
DROP TRIGGER check_account_update ON bs_account;
DROP TRIGGER check_account_insert ON bs_account;
DROP TRIGGER check_phone_update ON bs_phone;
DROP TRIGGER check_phone_insert ON bs_phone;
DROP TRIGGER check_business_update ON bs_business;
DROP TRIGGER check_business_insert ON bs_business;
DROP TRIGGER check_individual_update ON bs_individual;
DROP TRIGGER check_individual_insert ON bs_individual;
DROP TRIGGER check_user_update ON bs_user;
DROP TRIGGER check_user_insert ON bs_user;
DROP TRIGGER check_organization_update ON bs_organization;
DROP TRIGGER check_organization_insert ON bs_organization;
DROP TRIGGER check_person_insert ON bs_person;
DROP TRIGGER check_person_update ON bs_person;
DROP TRIGGER check_db_errors_update ON bs_db_errors;
DROP TRIGGER check_db_errors_insert ON bs_db_errors;

DROP FUNCTION public.account_checker();
DROP FUNCTION public.account_creator(INTEGER, DOUBLE PRECISION);
DROP FUNCTION public.address_creator(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR);
DROP FUNCTION public.alphabets_only(VARCHAR);
DROP FUNCTION public.alphanumeric_only(VARCHAR);
DROP FUNCTION public.business_checker();
DROP FUNCTION public.change_account_activity(VARCHAR);
DROP FUNCTION public.creation_transaction_pattern(VARCHAR, VARCHAR, VARCHAR, VARCHAR);
DROP FUNCTION public.customer_business_creator(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR);
DROP FUNCTION public.customer_business_updator(INTEGER, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR);
DROP FUNCTION public.customer_individual_creator(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR);
DROP FUNCTION public.customer_individual_updator(INTEGER, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR);
DROP FUNCTION public.db_errors_checker();
DROP FUNCTION public.get_account_transactions(INTEGER);
DROP FUNCTION public.get_categories();
DROP FUNCTION public.get_close_date(VARCHAR);
DROP FUNCTION public.get_customer_id(VARCHAR);
DROP FUNCTION public.individual_checker();
DROP FUNCTION public.make_login(VARCHAR, VARCHAR);
DROP FUNCTION public.make_transaction(VARCHAR, VARCHAR, VARCHAR, BOOLEAN);
DROP FUNCTION public.numeric_only(VARCHAR);
DROP FUNCTION public.organisation_checker();
DROP FUNCTION public.person_checker();
DROP FUNCTION public.phone_checker();
DROP FUNCTION public.random_account_num_creator();
DROP FUNCTION public.select_customer_accounts(INTEGER);
DROP FUNCTION public.select_customer_categories(INTEGER);
DROP FUNCTION public.select_customer_templates(INTEGER);
DROP FUNCTION public.select_customer_transactions_by_outgoing(VARCHAR);
DROP FUNCTION public.select_customer_transactions_by_pattern(VARCHAR);
DROP FUNCTION public.select_db_error_message(VARCHAR);
DROP FUNCTION public.select_individuals(VARCHAR, VARCHAR);
DROP FUNCTION public.select_organizations(VARCHAR);
DROP FUNCTION public.transaction_checker();
DROP FUNCTION public.user_checker();

ALTER TABLE public.bs_user DROP CONSTRAINT bs_user_person_id_fkey;
ALTER TABLE public.bs_template DROP CONSTRAINT bs_template_customer_id_fkey;
ALTER TABLE public.bs_template DROP CONSTRAINT bs_template_txn_id_fkey;
ALTER TABLE public.bs_phone DROP CONSTRAINT bs_phone_customer_id_fkey;
ALTER TABLE public.bs_individual DROP CONSTRAINT bs_individual_customer_id_fkey;
ALTER TABLE public.bs_individual DROP CONSTRAINT bs_individual_person_id_fkey;
ALTER TABLE public.bs_employee DROP CONSTRAINT bs_employee_office_id_fkey;
ALTER TABLE public.bs_employee DROP CONSTRAINT bs_employee_employee_id_fkey;
ALTER TABLE public.bs_customer_transaction_pattern DROP CONSTRAINT bs_customer_transaction_pattern_customer_id_fkey;
ALTER TABLE public.bs_customer_transaction_pattern DROP CONSTRAINT bs_customer_transaction_pattern_account_from_id_fkey;
ALTER TABLE public.bs_customer_transaction_pattern DROP CONSTRAINT bs_customer_transaction_pattern_account_to_id_fkey;
ALTER TABLE public.bs_customer_transaction_pattern DROP CONSTRAINT bs_customer_transaction_pattern_txn_cat_id_fkey;
ALTER TABLE public.bs_business DROP CONSTRAINT bs_business_customer_id_fkey;
ALTER TABLE public.bs_business DROP CONSTRAINT bs_business_org_id_fkey;
ALTER TABLE public.bs_transaction DROP CONSTRAINT bs_transaction_account_from_id_fkey;
ALTER TABLE public.bs_transaction DROP CONSTRAINT bs_transaction_account_to_id_fkey;
ALTER TABLE public.bs_transaction_category DROP CONSTRAINT bs_transaction_category_customer_id_fkey;
ALTER TABLE public.bs_office DROP CONSTRAINT bs_office_address_id_fkey;
ALTER TABLE public.bs_customer DROP CONSTRAINT bs_customer_address_id_fkey;
ALTER TABLE public.bs_account DROP CONSTRAINT bs_account_customer_id_fkey;
DROP TABLE public.bs_user;
DROP TABLE public.bs_template;
DROP TABLE public.bs_phone;
DROP TABLE public.bs_individual;
DROP TABLE public.bs_employee;
DROP TABLE public.bs_customer_transaction_pattern;
DROP TABLE public.bs_business;
DROP TABLE public.bs_transaction;
DROP TABLE public.bs_transaction_category;
DROP TABLE public.bs_office;
DROP TABLE public.bs_customer;
DROP TABLE public.bs_account;
DROP TABLE public.bs_person;
DROP TABLE public.bs_organization;
DROP TABLE public.bs_address;
DROP TABLE public.bs_db_errors;

DROP TYPE user_type;
DROP TYPE customer_type;
DROP TYPE person_sex;